spring.application.name=personaumg4
server.port=8080
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/programacion_3
spring.datasource.username=postgres
spring.datasource.password=1234bd
spring.jpa.hibernate.ddl-auto=update
spring.graphql.cors.allowed-origins=*
spring.graphql.cors.allowed-headers=*
spring.grap hql.cors.allowed-methods=*   